version: "3.8"

services:
  ros:
    build: . # Build from Dockerfile in the current directory
    # image: ros:humble-ros-core
    # container_name: ros_core
    tty: true
    stdin_open: true
    restart: unless-stopped
    network_mode: host # Use host networking mode here
    volumes:
      - .:/app
      - /dev:/dev # Mounting all /dev devices
      - ./microros_ws:/root/microros_ws
      # - ./src:/root/rover25_ws/src
      - $HOME/rover25_ws:/root/rover25_ws
    privileged: true # Add privileged mode here
    command: /bin/bash # Override default command to start a shell
    environment:
      # - ROS_DOMAIN_ID=10
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_LOCALHOST_ONLY=0
# Remove the networks section entirely
# networks:
#   ros_network:
#     driver: bridge
