# Vision System Configuration
# Jetson/Pi Device Configuration for Multi-Camera System

# Jetson/Pi Device Configuration
jetson_config:
  # Default backend host for Jetson/Pi devices to send RTP streams to
  default_backend_host: "192.168.1.100"
  
  # Default backend UDP port for Jetson/Pi devices (legacy heartbeat)
  default_backend_port: 9999
  
  # Default JPEG quality (1-100) - legacy, now unused
  default_jpeg_quality: 80
  
  # Default target FPS
  default_fps: 20
  
  # Camera capture settings
  capture_width: 640
  capture_height: 480
  
  # Heartbeat interval (seconds)
  heartbeat_interval: 5.0
  
  # Frame send interval (calculated from FPS)
  frame_interval: 0.05  # 1.0 / 20 FPS default
  
  # GStreamer settings for Jetson
  gstreamer_config:
    h264_bitrate: 512  # kbps
    h264_tune: "zerolatency"
    rtp_payload_type: 96
    rtp_config_interval: 1
    udp_buffer_size: 1048576  # 1MB
    frame_buffer_size: 65536
    max_frame_size: 60000
  
  # Camera configuration - no fixed port mapping
  # Jetson server will choose any available port dynamically

# Network Configuration
network_config:
  # Maximum retries for network operations
  max_retries: 3
  
  # Connection timeout (seconds)
  connection_timeout: 5.0
  
  # Socket buffer sizes
  udp_send_buffer_size: 1048576  # 1MB
  udp_recv_buffer_size: 1048576  # 1MB

# Logging Configuration
logging_config:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S" 