# Vision System Configuration
# Jetson/Pi Device Configuration for Multi-Camera System

# Jetson/Pi Device Configuration
jetson_config:
  # Default backend host for Jetson/Pi devices to send RTP streams to
  default_backend_host: "192.168.1.100"
  
  # Default backend UDP port for Jetson/Pi devices (legacy heartbeat)
  default_backend_port: 9999
  
  # Default JPEG quality (1-100) - legacy, now unused
  default_jpeg_quality: 80
  
  # Default target FPS
  default_fps: 20
  
  # Camera capture settings
  capture_width: 640
  capture_height: 480
  
  # Heartbeat interval (seconds)
  heartbeat_interval: 5.0
  
  # Frame send interval (calculated from FPS)
  frame_interval: 0.05  # 1.0 / 20 FPS default
  
  # GStreamer settings for Jetson
  gstreamer_config:
    h264_bitrate: 512  # kbps
    h264_tune: "zerolatency"
    rtp_payload_type: 96
    rtp_config_interval: 1
    udp_buffer_size: 1048576  # 1MB
    frame_buffer_size: 65536
    max_frame_size: 60000
    min_bitrate: 128  # kbps
    max_bitrate: 2048  # kbps
    min_fps: 5
    max_fps: 30
    pipeline_formats:
      mjpg:
        caps: "image/jpeg,width=640,height=480,framerate=30/1"
        elements: [
          "jpegdec",
          "videoconvert",
          "video/x-raw,format=NV12"
        ]
      yuyv:
        caps: "video/x-raw,format=YUY2,width=640,height=480,framerate=20/1"
        elements: [
          "videoconvert",
          "video/x-raw,format=NV12"
        ]
      raw:
        caps: "video/x-raw,width={width},height={height},framerate={fps}/1"
        elements: [
          "videoconvert"
        ]
    encoder_elements: [
      "x264enc tune={tune} bitrate={bitrate}",
      "h264parse",
      "rtph264pay config-interval=1 pt=96"
    ]

# Network Configuration
network_config:
  # Maximum retries for network operations
  max_retries: 3
  
  # Connection timeout (seconds)
  connection_timeout: 5.0
  
  # Socket buffer sizes
  udp_send_buffer_size: 1048576  # 1MB
  udp_recv_buffer_size: 1048576  # 1MB
  
  # Command socket settings
  command_port_offset: 1  # backend_port + 1
  command_timeout: 1.0  # seconds
  
  # UDP packet settings
  max_packet_size: 65507  # Maximum UDP packet size
  header_size: 13  # camera_id_len(1) + packet_num(2) + total_packets(2) + timestamp(8)
  max_payload_size: 65494  # max_packet_size - header_size

# Logging Configuration
logging_config:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # Log file settings
  file_enabled: true
  file_path: "/var/log/vision_server.log"
  file_max_size: 10485760  # 10MB
  file_backup_count: 5
  
  # Console output settings
  console_enabled: true
  console_format: "%(levelname)s: %(message)s"